modLoader = "javafml"
loaderVersion = "[0,999]"
license = "MPL-2"

[[mods]]
modId = "nyx"
version = "${version}"
displayName = "Nyx"
authors = "SciRave"
description = '''
A multi-version mob/difficulty overhaul
'''
logoFile = "nyx.icon.png"
